### ISSUE TITLE
JsonReader 反序列化方式遇到错误了，求教

### ISSUE THREAD

**Issue by CreateChance** [kanyun-inc/Kudos#20]
我的代码如下：
```kotlin
fun main() {
    val jsonString = """
        {
            "name": "Tom",
            "age": 18,
            "address": "Beijing"
        }
    """.trimIndent()

    val user = KudosAndroidJsonReader.fromJson<User>(jsonString, User::class.java)

    println("反序列化结果: $user")
}

@Kudos
abstract class User(
    @SerializedName("name")
    val name: String,

    @SerializedName("age")
    val age: Int,

    @SerializedName("address")
    val address: String,

    @SerializedName("email")
    val email: String = "default@example.org"
)
```
build.gradle 中也开启了 jsonreader 支持：
```kotlin
plugins {
    kotlin("jvm")
    id("com.kanyun.kudos") version "1.9.20-1.1.1"
}

kudos {
    androidJsonReader = true
}
```
然后编译时遇到如下错误：
```
Executing ':kudos_gson3:classes'...

> Task :kudos_gson3:checkKotlinGradlePluginConfigurationErrors
> Task :kudos_gson3:processResources NO-SOURCE

> Task :kudos_gson3:compileKotlin FAILED
2 actionable tasks: 2 executed
e: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:197)
	at com.kanyun.kudos.compiler.KudosFromJsonFunctionBuilder.generateBody(KudosFromJsonFunctionBuilder.kt:96)
	at com.kanyun.kudos.compiler.KudosIrClassTransformer.generateFromJson(KudosIrClassTransformer.kt:407)
	at com.kanyun.kudos.compiler.KudosIrClassTransformer.transform(KudosIrClassTransformer.kt:102)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitClass(KudosIrTransformer.kt:45)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:111)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitClass(KudosIrTransformer.kt:30)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitClass(KudosIrTransformer.kt:30)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:73)
	at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:37)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitElement(KudosIrTransformer.kt:37)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:190)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitPackageFragment(KudosIrTransformer.kt:30)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:200)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitFile(KudosIrTransformer.kt:30)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:198)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitFile(KudosIrTransformer.kt:30)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitFile(KudosIrTransformer.kt:30)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:31)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.acceptChildren(IrModuleFragment.kt:48)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitElement(KudosIrTransformer.kt:37)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:160)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitModuleFragment(KudosIrTransformer.kt:30)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:158)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitModuleFragment(KudosIrTransformer.kt:30)
	at com.kanyun.kudos.compiler.KudosIrTransformer.visitModuleFragment(KudosIrTransformer.kt:30)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.accept(IrModuleFragment.kt:42)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
	at com.kanyun.kudos.compiler.KudosIrGenerationExtension.generate(KudosIrGenerationExtension.kt:29)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:225)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:107)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:255)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:59)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:224)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:463)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:62)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:477)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:400)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:281)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:125)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:657)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:105)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1624)
	at jdk.internal.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kudos_gson3:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 269ms
```

**Comment by RicardoJiang** [comment]
1. 抛出 e: java.util.NoSuchElementException: List is empty 异常的原因是 JsonReader 只在 Android 平台内置，看示例代码你应该是在电脑上运行的？
2. 此外，反序列化时，User 似乎不应该是抽象类？

**Comment by CreateChance** [comment]
> 1. 抛出 e: java.util.NoSuchElementException: List is empty 异常的原因是 JsonReader 只在 Android 平台内置，看示例代码你应该是在电脑上运行的？
> 2. 此外，反序列化时，User 似乎不应该是抽象类？

确实是，我是在纯 kotlin 项目中测试的，没有在 android 中测试，在 android 项目中是 OK 的，乌龙了，抱歉。
另外，User 类确实不应该是抽象的。

**Comment by CreateChance** [comment]
kudos 是很棒的项目，可以解决一直困扰的实际问题，感谢～
